export const APP_TITLE = "Emerging Coders Membership Directory";

export enum Paths {
  Home = "/",
  Signup = "/signup",
  Login = "/login",
  Dashboard = "/dashboard",
}

export const SIGNUP_STEPS = [
  { id: 1, name: "Personal Information" },
  { id: 2, name: "Academic Information" },
  { id: 3, name: "Student Status" },
  { id: 4, name: "Password" },
];

export const HOME_SCHOOLS = [
  "Weinberg College of Arts and Sciences",
  "McCormick School of Engineering",
  "School of Communication",
  "School of Education and Social Policy",
  "Medill School of Journalism, Media, Integrated Marketing Communications",
  "Bienen School of Music",
  "School of Professional Studies",
];

export const GENDER_IDENTITIES = [
  "Cisgender Male",
  "Cisgender Female",
  "Nonbinary",
  "Pangender",
  "Other",
  "Prefer not to say",
];

export const PRONOUNS = [
  "She/Her",
  "She/They",
  "He/Him",
  "He/They",
  "They/Them",
  "Other",
  "Prefer not to say",
];

export const MAJORS = [
  "Computer Science",
  "Computer Engineering",
  "Electrical Engineering",
  "Data Science",
  "Mechanical Engineering",
  "Industrial Engineering",
  "Biomedical Engineering",
  "Chemical Engineering",
  "Civil Engineering",
  "Materials Science and Engineering",
  "Applied Mathematics",
  "Mathematics",
  "Statistics",
  "Physics and Astronomy",
  "Cognitive Science",
  "Neuroscience",
  "Biological Sciences",
  "Chemistry",
  "Environmental Engineering",
  "Earth and Planetary Sciences",
  "Manufacturing & Design Engineering)",
  "Integrated Engineering Studies",
  "Biotechnology and Biochemical Engineering",
  "Environmental Sciences",
  "Architectural Engineering and Design",
  "Economics",
  "Learning Sciences",
  "Integrated Science Program",
  "Human Communication Sciences",
  "Psychology",
  "Linguistics",
  "Philosophy",
  "Communication Studies",
  "Journalism",
  "Business Institutions",
  "Entrepreneurship",
  "Learning and Organizational Change",
  "Science in Human Culture",
  "African Studies",
  "American Studies",
  "Anthropology",
  "Arabic",
  "Art History",
  "Arts Administration",
  "Art Theory and Practice",
  "Asian American Studies",
  "Asian Humanities",
  "Asian Languages and Cultures",
  "Black Studies",
  "Business Enterprise",
  "Business German",
  "Catholic Studies",
  "Central Southeastern European Studies",
  "Civic Engagement",
  "Classics",
  "Combined Engineering and Communication Program",
  "Combined Music & Engineering Program",
  "Combined Music and Communication Program",
  "Comparative Literary Studies",
  "Cooperative Engineering Education Program",
  "Critical Theory",
  "Dance",
  "English: Creative Writing",
  "English: Creative Writing (cross-genre)",
  "English: Creative Writing (sequence-based)",
  "English: Literature",
  "Environmental Policy and Culture",
  "Film and Media Studies",
  "French",
  "Gender and Sexuality Studies",
  "General Music",
  "Geography",
  "German",
  "German Studies",
  "Global Health Studies",
  "Greek",
  "Hebrew Studies",
  "History",
  "Human Development in Context",
  "Humanities",
  "Humanities (part-time)",
  "Integrated Marketing Communications (IMC) Undergraduate Certificate",
  "International Studies",
  "Italian",
  "Jewish Studies",
  "Kellogg Program for Undergraduates (certificate)",
  "Latin",
  "Latina and Latino Studies",
  "Latin American and Caribbean Studies",
  "Leadership",
  "Legal Studies",
  "Middle East North African Studies",
  "Music Cognition",
  "Music Composition",
  "Music Criticism",
  "Music Education",
  "Musicology",
  "Music Performance: Brass",
  "Music Performance: Jazz Studies",
  "Music Performance: Percussion",
  "Music Performance: Piano",
  "Music Performance: Strings",
  "Music Performance: Voice & Opera",
  "Music Performance: Woodwinds",
  "Music Studies: Cognition",
  "Music Studies: Composition",
  "Music Studies: Music Education",
  "Music Studies: Musicology",
  "Music Studies: Music Theory",
  "Music Technology",
  "Music Theatre (certificate)",
  "Music Theory",
  "Native American and Indigenous Studies",
  "Performance Studies",
  "Political Science",
  "Portuguese Language and Lusophone Cultures",
  "Radio/Television/Film",
  "Religious Studies",
  "Russian and East European Studies",
  "Russian Language, Literature, and Culture",
  "Secondary Teaching",
  "Segal Design",
  "Social Policy",
  "Social Sciences (part-time)",
  "Sociology",
  "Sound Design",
  "Spanish",
  "Sustainability and Energy",
  "Theatre",
  "Transportation and Logistics",
  "World Literature",
];
